### ISSUE TITLE
API problem with querying exchange rates from and to EUR

### ISSUE THREAD

**Issue by mikestempien** [jin5354/alfred3-workflow-CurrencyConvert#11]
Having added EUR to the list and trying to do `cy 500EUR` results in an error from the API:
https://exchangeratesapi.io/api/latest?base=EUR&symbols=USD,GBP,CHF,PLN,EUR
`{ "error": "Symbols 'USD,GBP,CHF,PLN,EUR' are invalid for date 2018-06-07." }`

A solution would be to remove queried currency from the symbols array:
https://exchangeratesapi.io/api/latest?base=EUR&symbols=USD,GBP,CHF,PLN

**Comment by jin5354** [comment]
Fixed, please update to [version v1.4+](https://github.com/jin5354/alfred3-workflow-CurrencyConvert/releases).
