### ISSUE TITLE
Converter not working any longer

### ISSUE THREAD

**Issue by cbiggins** [jin5354/alfred3-workflow-CurrencyConvert#14]
Looks like perhaps a change at exchangeratesapi.io ?

http://exchangeratesapi.io/api/latest
needs to change to 
http://api.exchangeratesapi.io/latest

**Comment by cbiggins** [comment]
nm, looks like this PR sorts it - https://github.com/jin5354/alfred3-workflow-CurrencyConvert/pull/13

**Comment by jin5354** [comment]
Done. [v1.5](https://github.com/jin5354/alfred3-workflow-CurrencyConvert/releases/tag/v1.5)
