### ISSUE TITLE
RUB currency

### ISSUE THREAD

**Issue by alexman000** [jin5354/alfred3-workflow-CurrencyConvert#19]
How can I add RUB currency using command add-cy?

**Comment by jin5354** [comment]
Exchange reference rates are fetched from the [European Central Bank](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html). It is a pity that ECB doesn't provide RUB rate now. If there is a reliable, stable, and more full-scale rates API provider which can provide RUB rate I'd be glad to migrate. :)
