### ISSUE TITLE
Make full query specification return a single row

### ISSUE THREAD

**Issue by andybergon** [jin5354/alfred3-workflow-CurrencyConvert#2]
I really nice feature would be to have only 1 line when we do a full specification.

![image](https://user-images.githubusercontent.com/5220825/31415162-9654e2ea-ae19-11e7-80d4-0a7e682a9f13.png)

In this case it will be very nice to have only the GBP line! :)

**Comment by jin5354** [comment]
Sorry for the delay. See [v1.1](https://github.com/jin5354/alfred3-workflow-CurrencyConvert/releases/tag/v1.1)
