### ISSUE TITLE
Can't use if i turn on system proxy

### ISSUE THREAD

**Issue by sephrioth** [jin5354/alfred3-workflow-CurrencyConvert#24]
If i set the system http & https proxy to 127.0.0.1:6152, here is the error log.

ERROR: Currency Convert[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "127.0.0.1:6152127.0.0.1:6152" (URI::InvalidURIError)

Here is the log when i set proxy to http/https proxy to 127.0.0.1:6152

ERROR: Currency Convert[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "127.0.0.1:6152" (URI::InvalidURIError)

**Comment by btyh17mxy** [comment]
run into this error too, and I found out that is because the http_proxy environment does not start with "http://". also I have found a workaround, add these to convert.rb (after line 15).

``` ruby
http_proxy = ENV["http_proxy"]
unless http_proxy.to_s.empty?
    unless http_proxy.start_with?("http")
        ENV["http_proxy"] = "http://#{ENV["http_proxy"]}"
    end
end
```

**Comment by sephrioth** [comment]
Work like a charm, thank you. @btyh17mxy

**Comment by btyh17mxy** [comment]
> Work like a charm, thank you. @btyh17mxy

Surge user I presume?

**Comment by sephrioth** [comment]
> > Work like a charm, thank you. @btyh17mxy
> 
> Surge user I presume?

Yes, but how do you find it out?
