### ISSUE TITLE
Allow white space between amount and currency

### ISSUE THREAD

**Issue by andybergon** [jin5354/alfred3-workflow-CurrencyConvert#3]
I don't know how much effort it will require but it will be nice if we were allowed to have a white space between the amount and the currency as a lot of people is used to type this way.

![image](https://user-images.githubusercontent.com/5220825/31415271-39f9d798-ae1a-11e7-94fd-31aed00a2218.png)

I'll try to give a look at the code and see if I can help with that :)

**Comment by jkaving** [comment]
I just made a pull request that fixes this.
